### ISSUE TITLE
[FEAT] 제품 상세 페이지

### ISSUE THREAD

**Issue by yeoncheong** [DATE-Naeun/Naeun-CLIENT#10]
## 문제 상황
제품 상세 페이지
![image](https://github.com/DATE-Naeun/Naeun-CLIENT/assets/102457618/c8e239bd-487e-4c2d-a5af-8c9aa66893db)

## 반영 형태 및 SEQUENCE
- ViewPager2로 (성분보기 / 리뷰 쓰기, 보기) 선택
- Indicator로 사진 좌우 스와이프 가능하게 하기
- 중첩 RecyclerView로 리뷰 보여주기
- ExpandedList로 성분 표시 보여주기

## TODO
- [x] [UI] 제품 사진 및 간단한 정보
- [x] [UI] 성분보기
- [ ] [UI] 리뷰 쓰기/보기
- [ ] [UI] 리뷰 쓰기
- [ ] [UI] 성분 분류
- [ ] [FEAT] ViewPager2로 (성분보기 / 리뷰 쓰기, 보기) 선택
- [ ] [FEAT] Indicator로 사진 좌우 스와이프 가능하게 하기
- [ ] [FEAT] 중첩 RecyclerView로 리뷰 보여주기
- [ ] [FEAT] ExpandedList로 성분 표시 보여주기
