### ISSUE TITLE
[FEAT] 피부타입 선택 (간편 / 질문지)

### ISSUE THREAD

**Issue by visionWWW** [DATE-Naeun/Naeun-CLIENT#3]
## 문제 상황
피부타입 선택 (간편 / 질문지) UI

<img width="371" alt="image" src="https://github.com/DATE-Naeun/Naeun-CLIENT/assets/62435316/1af5ca2c-04d1-4ca4-8ca0-d791d8ab4e68">

## 반영 형태 및 SEQUENCE
- Viewpager2로 (간편 / 질문지) 선택

## TODO
- [ ] [UI] 간편 선택
- [ ] [UI] 질문지 선택
- [ ] [FEAT] Viewpager2로 (간편 / 질문지) 선택
